pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)

    repositories {
        google()
        mavenCentral()

        // Mozilla GeckoView repository
        maven {
            url "https://maven.mozilla.org/maven2/"
        }
    }
}

rootProject.name = "Footbolive"

include(":app")
