plugins {
    id 'com.android.application'
}

android {
    namespace 'com.deeprows.football'
    compileSdk 35

    defaultConfig {
        applicationId 'com.deeprows.football'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    // AndroidX Splash Screen
    implementation 'androidx.core:core-splashscreen:1.0.1'

    // Media3 / ExoPlayer
    implementation 'androidx.media3:media3-exoplayer:1.11.0'
    implementation 'androidx.media3:media3-ui:1.11.0'
}
